[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:397 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:402 Cutting network for postgresql/2